# Form implementation generated from reading ui file 'Calculate the number pi.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(388, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #343a40;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topInnFrame = QtWidgets.QWidget(self.centralwidget)
        self.topInnFrame.setStyleSheet("* {\n"
"    background-color: #212529;\n"
"}\n"
"#topInnFrame {\n"
"    border: 3px solid #000814;\n"
"}")
        self.topInnFrame.setObjectName("topInnFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.topInnFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topFrame = QtWidgets.QWidget(self.topInnFrame)
        self.topFrame.setStyleSheet("#botFrame {\n"
"\n"
"}")
        self.topFrame.setObjectName("topFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.topFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.right_part = QtWidgets.QWidget(self.topFrame)
        self.right_part.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.right_part.setObjectName("right_part")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.right_part)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelLengthStart = QtWidgets.QLabel(self.right_part)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(28)
        font.setItalic(True)
        self.labelLengthStart.setFont(font)
        self.labelLengthStart.setStyleSheet("color: #e9ecef;")
        self.labelLengthStart.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelLengthStart.setObjectName("labelLengthStart")
        self.horizontalLayout_2.addWidget(self.labelLengthStart)
        self.lineEdit = QtWidgets.QLineEdit(self.right_part)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quant Antiqua")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lineEdit.setStyleSheet("color: #fca311;\n"
"background-color: #000814;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_7.addWidget(self.right_part)
        self.left_part = QtWidgets.QWidget(self.topFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_part.sizePolicy().hasHeightForWidth())
        self.left_part.setSizePolicy(sizePolicy)
        self.left_part.setObjectName("left_part")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.left_part)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelLengthEnd = QtWidgets.QLabel(self.left_part)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(28)
        font.setItalic(True)
        self.labelLengthEnd.setFont(font)
        self.labelLengthEnd.setStyleSheet("color: #e9ecef;")
        self.labelLengthEnd.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelLengthEnd.setObjectName("labelLengthEnd")
        self.horizontalLayout.addWidget(self.labelLengthEnd)
        self.inputEnd = QtWidgets.QLineEdit(self.left_part)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEnd.sizePolicy().hasHeightForWidth())
        self.inputEnd.setSizePolicy(sizePolicy)
        self.inputEnd.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quant Antiqua")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.inputEnd.setFont(font)
        self.inputEnd.setStyleSheet("color: #fca311;\n"
"background-color: #000814;")
        self.inputEnd.setFrame(True)
        self.inputEnd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inputEnd.setObjectName("inputEnd")
        self.horizontalLayout.addWidget(self.inputEnd)
        self.verticalLayout_7.addWidget(self.left_part)
        self.verticalLayout_2.addWidget(self.topFrame)
        self.line = QtWidgets.QFrame(self.topInnFrame)
        self.line.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.line.setAutoFillBackground(False)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.botFrame = QtWidgets.QWidget(self.topInnFrame)
        self.botFrame.setStyleSheet("#botFrame {\n"
"\n"
"}")
        self.botFrame.setObjectName("botFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.botFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelDotsNumber = QtWidgets.QLabel(self.botFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelDotsNumber.setFont(font)
        self.labelDotsNumber.setStyleSheet("color: #e9ecef;")
        self.labelDotsNumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelDotsNumber.setObjectName("labelDotsNumber")
        self.verticalLayout_4.addWidget(self.labelDotsNumber)
        self.inputDots = QtWidgets.QLineEdit(self.botFrame)
        font = QtGui.QFont()
        font.setFamily("Quant Antiqua")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.inputDots.setFont(font)
        self.inputDots.setStyleSheet("color: #fca311;\n"
"background-color: #000814;")
        self.inputDots.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inputDots.setObjectName("inputDots")
        self.verticalLayout_4.addWidget(self.inputDots)
        self.verticalLayout_2.addWidget(self.botFrame)
        self.verticalLayout.addWidget(self.topInnFrame)
        self.botInnFrame = QtWidgets.QWidget(self.centralwidget)
        self.botInnFrame.setStyleSheet("background-color: #212529;border: 3px solid #000814;")
        self.botInnFrame.setObjectName("botInnFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.botInnFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.botInnFrame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #fca311;\n"
"    background-color: #000814;\n"
"    border: 2px solid #e9ecef;\n"
"}\n"
"QPushButton::Pressed {\n"
"    color: green;\n"
"}")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.botInnFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelLengthStart.setText(_translate("MainWindow", "x<sub>start</sub>"))
        self.lineEdit.setText(_translate("MainWindow", "-1.0"))
        self.labelLengthEnd.setText(_translate("MainWindow", "x<sub>end</sub>"))
        self.inputEnd.setText(_translate("MainWindow", "1.0"))
        self.labelDotsNumber.setText(_translate("MainWindow", "Number of dots"))
        self.inputDots.setText(_translate("MainWindow", "10000"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
